name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# 1. Configuration des Catégories pour le Changelog
categories:
  - title: '🚀 Nouvelles Fonctionnalités'
    labels:
      - 'feature'
  - title: '🐛 Corrections de Bugs'
    labels:
      - 'fix'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '🎨 Style & Formatage'
    labels:
      - 'style'
  - title: '♻️ Refactoring'
    labels:
      - 'refactor'
  - title: '🧪 Tests'
    labels:
      - 'test'
  - title: '⚙️ Tâches Techniques'
    labels:
      - 'chore'
  - title: '🏭 CI/CD & DevOps'
    labels:
      - 'cicd'

# 2. Configuration de l'Autolabeler (Le "Traducteur")
# Gauche = Label GitHub / Droite = Le début de votre titre de commit (Regex)
autolabeler:
  - label: 'feature'
    regex:
      - '^feat(\(.*\))?:'      # Detecte "feat:" ou "feat(app):" -> Met le label "feature"
      - '^feature(\(.*\))?:'
  - label: 'fix'
    regex:
      - '^fix(\(.*\))?:'       # Detecte "fix:" -> Met le label "fix"
      - '^bug(\(.*\))?:'
  - label: 'documentation'
    regex:
      - '^docs(\(.*\))?:'      # Detecte "docs:" -> Met le label "documentation"
  - label: 'style'
    regex:
      - '^style(\(.*\))?:'     # Detecte "style:" -> Met le label "style"
  - label: 'refactor'
    regex:
      - '^refactor(\(.*\))?:'  # Detecte "refactor:" -> Met le label "refactor"
  - label: 'test'
    regex:
      - '^test(\(.*\))?:'      # Detecte "test:" -> Met le label "test"
  - label: 'chore'
    regex:
      - '^chore(\(.*\))?:'     # Detecte "chore:" -> Met le label "chore"
  - label: 'cicd'
    regex:
      - '^ci(\(.*\))?:'        # Detecte "ci:" -> Met le label "cicd"
      - '^cicd(\(.*\))?:'

# 3. Calcul automatique du numéro de version (SemVer)
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'fix'
      - 'chore'
      - 'refactor'
      - 'documentation'
      - 'style'
      - 'test'
      - 'cicd'

template: |
  ## Modifications
  $CHANGES